export const modelStore = [
  {id: 0, text: 'Выбрать все'},
  {id: 1, text: '3'},
  {id: 2, text: '323'},
  {id: 3, text: '6'},
  {id: 4, text: '626'},
  {id: 5, text: 'CX-30'},
  {id: 6, text: 'CX-5'},
  {id: 7, text: 'CX-7'},
  {id: 8, text: 'CX-9'},
  {id: 9, text: 'Demino'},
  {id: 10, text: 'Familia'},
  {id: 11, text: 'MPV'},
  {id: 12, text: 'Premacy'},
  {id: 13, text: 'CX-9'},
];